version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check for updates once a week
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'America/New_York'
    # Specify labels for pull requests
    labels:
      - 'dependencies'
      - 'npm'
      - 'security'
    # Set version update strategy
    versioning-strategy: auto
    # Limit the number of open pull requests for version updates
    open-pull-requests-limit: 10
    # Allow up-to-date branches to be rebased
    rebase-strategy: auto
    # Group all minor and patch updates together
    groups:
      dependencies:
        patterns:
          - '*'
      security-updates:
        patterns:
          - '*'
        update-types:
          - 'patch'
    # Specify reviewers for the pull requests
    reviewers:
      - 'aenima'
    # Specify assignees for the pull requests
    assignees:
      - 'aenima'
    # Set commit message prefix
    commit-message:
      prefix: 'npm'
      include: 'scope'
    ignore:
      # Ignore major version updates for React
      - dependency-name: 'react'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-dom'
        update-types: ['version-update:semver-major']
    # Add security update configuration
    security-updates-only: false
    # Add vulnerability alerts
    vulnerability-alerts:
      enabled: true
